CREATE TABLE IF NOT EXISTS AF (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	numero INTEGER NOT NULL UNIQUE,
	fornecedor TEXT NOT NULL,
	descricao TEXT NOT NULL,
	data_inicio TEXT NOT NULL,
	data_fim TEXT NOT NULL,
	status BOOLEAN NOT NULL
);
