CREATE TABLE IF NOT EXISTS AF (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Contrato_id INTEGER NOT NULL,
	principal BOOLEAN NOT NULL,
	numero INTEGER NOT NULL UNIQUE,
	fornecedor TEXT NOT NULL,
	descricao TEXT,
	data_inicio TEXT NOT NULL,
	data_fim TEXT NOT NULL,
	status BOOLEAN NOT NULL,
	FOREIGN KEY (Contrato_id) REFERENCES Contrato(id) ON DELETE RESTRICT
);
