CREATE TABLE IF NOT EXISTS Item (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	AF_id INTEGER NOT NULL,
	Local_id INTEGER NOT NULL,
	descricao TEXT NOT NULL,
	banda_maxima INTEGER NOT NULL,
	banda_instalada INTEGER NOT NULL,
	data_instalacao TEXT NOT NULL,
	quantidade INTEGER NOT NULL,
	status BOOLEAN NOT NULL,
	FOREIGN KEY (AF_id) REFERENCES AF(id) ON DELETE RESTRICT,
	FOREIGN KEY (Local_id) REFERENCES Local(id) ON DELETE RESTRICT
);
