CREATE TABLE IF NOT EXISTS Valor (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Item_id INTEGER NOT NULL,
	valor INTEGER NOT NULL,
	data_inicio TEXT NOT NULL,
	data_fim TEXT,
	FOREIGN KEY (Item_id) REFERENCES Item(id) ON DELETE CASCADE
) STRICT;
